framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            places:
                - submitted
                - ham
                - potencial_spam
                - spam
                - rejected
                - ready
                - published
            transitions:
                accept:
                    from: submitted
                    to: ham
                might_be_spam:
                    from: submitted
                    to: potencial_spam
                reject_spam:
                    from: submitted
                    to: spam
                publish:
                    from: potencial_spam
                    to: ready
                reject:
                    from: potencial_spam
                    to: rejected
                publish_ham:
                    from: ham
                    to: ready
                reject_ham:
                    from: ham
                    to: rejected
                optimize:
                    from: ready
                    to: published
